version: "3"
services:
  app-two:
    environment:
      CONFIG_PROFILE: $CONFIG_PROFILE
      CONFIG_LOGIN_PWD: 12345
    image: itmabo/app-two:latest
    volumes:
      - /home/log:/home/log
#    networks:
#      - tonynet-a
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
#networks:
#  tonynet-a:
#    external:
#      name: tonynet